CREATE TABLE IF NOT EXISTS "USERS" (
    ID NUMBER (19) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    "PASSWORD" VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PHONE (
    ID NUMBER (19) PRIMARY KEY AUTO_INCREMENT,
    NUMBER VARCHAR2(12) NOT NULL UNIQUE,
    CITYCODE VARCHAR2(5) NOT NULL UNIQUE,
    COUNTRYCODE VARCHAR2(5) NOT NULL UNIQUE,
    USER_ID NUMBER (19) NOT NULL,
    CONSTRAINT PHONE_USER_FK FOREIGN KEY (USER_ID) REFERENCES "USERS" (ID)
);