CREATE TABLE IF NOT EXISTS "USERS" (
    ID NUMBER (19) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    "PASSWORD" VARCHAR2(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONES (
    ID NUMBER (19) PRIMARY KEY AUTO_INCREMENT,
    NUMBER VARCHAR2(12) NOT NULL,
    CITYCODE VARCHAR2(5) NOT NULL,
    COUNTRYCODE VARCHAR2(5) NOT NULL,
    USER_ID NUMBER (19),
    CONSTRAINT PHONE_USER_FK FOREIGN KEY (USER_ID) REFERENCES "USERS" (ID)
);